# Generated by Django 5.0.2 on 2024-02-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Phn_number', models.IntegerField(max_length=100)),
                ('Adhar_card', models.IntegerField(max_length=100)),
            ],
        ),
    ]
